### ISSUE TITLE
Support JL<4.6 in latest stable Jupyter Chat?

### ISSUE THREAD

**Issue by dlqqq** [jupyterlab/jupyter-chat#471]
## Description

This PR bumped the minimum requirements of the `jupyterlab-chat` labextension to packages only available in JupyterLab v4.6+ : https://github.com/jupyterlab/jupyter-chat/pull/453

The problem is that now `jupyterlab-chat` requires `jupyter-collaboration`, but there is no stable release of that package that supports the new `jupyter_ydoc` v4 upgrade introduced in JL v4.6. This means that by default, almost all users get a broken environment when installing this:

- For users with JL <4.6 users, installing `jupyter-ai~=3.1` or `jupyterlab-chat~=0.23` results in this error when running `jupyter labextension list`:

```
$ jupyter labextension list
JupyterLab v4.5.10
/private/tmp/jai-compat/.venv/share/jupyter/labextensions
        jupyterlab-eventlistener-extension v0.4.0 enabled OK (python, jupyterlab_eventlistener)
        jupyterlab_pygments v0.3.0 enabled OK (python, jupyterlab_pygments)
        jupyterlab-notebook-awareness v0.1.0 enabled OK (python, jupyterlab_notebook_awareness)
        jupyterlab-chat-extension v0.23.0 enabled  X (python, jupyterlab_chat)
        jupyterlab-commands-toolkit v0.1.6 enabled OK (python, jupyterlab_commands_toolkit)
        @jupyter-ai/chat-commands v0.0.4 enabled OK (python, jupyter_ai_chat_commands)
        @jupyter-ai/persona-manager v0.1.2 enabled OK (python, jupyter_ai_persona_manager)
        @jupyter-ai/acp-client v0.2.1 enabled OK (python, jupyter_ai_acp_client)
        @jupyter-ai/router v0.0.5 enabled OK (python, jupyter_ai_router)
        @jupyter-ai-contrib/server-documents v0.3.1 enabled OK (python, jupyter_server_documents)
        @jupyter/collaboration-extension v4.4.1 enabled OK (python, jupyter-collaboration-ui)
        @jupyter/docprovider-extension v4.4.1 enabled OK (python, jupyter-docprovider)


"jupyterlab-chat-extension@0.23.0" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab                  Extension       Package
>=4.5.10 <4.6.0             >=4.6.0 <5.0.0  @jupyterlab/application
>=4.6.10 <4.7.0             >=4.7.0 <5.0.0  @jupyterlab/apputils
>=4.5.10 <4.6.0             >=4.6.0 <5.0.0  @jupyterlab/codemirror
>=6.5.10 <6.6.0             >=6.6.0 <7.0.0  @jupyterlab/coreutils
>=4.5.10 <4.6.0             >=4.6.0 <5.0.0  @jupyterlab/filebrowser
>=4.5.10 <4.6.0             >=4.6.0 <5.0.0  @jupyterlab/launcher
>=4.5.10 <4.6.0             >=4.6.0 <5.0.0  @jupyterlab/notebook
>=4.5.10 <4.6.0             >=4.6.0 <5.0.0  @jupyterlab/rendermime
>=7.5.10 <7.6.0             >=7.6.0 <8.0.0  @jupyterlab/services
>=4.5.10 <4.6.0             >=4.6.0 <5.0.0  @jupyterlab/settingregistry
>=4.5.10 <4.6.0             >=4.6.0 <5.0.0  @jupyterlab/translation
>=4.5.10 <4.6.0             >=4.6.0 <5.0.0  @jupyterlab/ui-components
```

- For users with JL >=4.6, just installing `jupyterlab-chat==0.23.0`, remarkably, still does not work out of the box. This is because `jupyterlab-chat` requires `jupyter-collaboration`, and there is still no official release that supports the new Jupyter YDoc v4 upgrade. So most JL >=4.6 users will get this error:

```
$ jupyter labextension list
JupyterLab v4.6.2
/private/tmp/jc-jl46/.venv/share/jupyter/labextensions
        jupyterlab_pygments v0.3.0 enabled OK (python, jupyterlab_pygments)
        jupyterlab-chat-extension v0.23.0 enabled OK (python, jupyterlab_chat)
        @jupyter/collaboration-extension v4.4.1 enabled  X (python, jupyter-collaboration-ui)
        @jupyter/docprovider-extension v4.4.1 enabled  X (python, jupyter-docprovider)


"@jupyter/collaboration-extension@4.4.1" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab    Extension         Package
>=4.0.0-b1 <5.0.0>=2.1.3 <3.0.0||>=3.0.0 <4.0.0@jupyter/ydoc



"@jupyter/docprovider-extension@4.4.1" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab    Extension         Package
>=4.0.0-b1 <5.0.0>=2.1.3 <3.0.0||>=3.0.0 <4.0.0@jupyter/ydoc
```

As far as I can tell, the only way to not get a broken environment is to run this command when installing the new Jupyter Chat release:

```
pip install 'jupyterlab-chat>=0.23.0,<0.24' 'jupyterlab>=4.6,<4.7' 'jupyter-collaboration>=5.0.0a0' --prerelease=allow
```

## Reproduce

Create `venv`s and run `jupyter labextension list` as shown above.

## Expected behavior

Jupyter Chat v0.23.0 should ideally work for JL <4.6 and JL >=4.6. However, until an official release of Jupyter Collaboration v5 is out, users will have to manually install the v5.0.0a0 pre-release as most package managers won't include pre-releases by default.

Since JL >=4.6 support won't happen without manual intervention, I recommend we at least support JL <4.6 out-of-the-box. That means loosening the ranges from https://github.com/jupyterlab/jupyter-chat/pull/453 to include JL <4.6 versions. I don't think we require any APIs exclusive to JL >=4.6 so this should be safe, we just need to investigate the issue that @brichet reported more closely. I suspect we can solve this using the `resolutions` field in `package.json`.

And on top of all of this, it would be good to add test coverage that ensures `jupyter labextension list` doesn't report any errors for JL <4.6, at least until the API truly requires JL >=4.6.

**Comment by krassowski** [comment]
> For users with JL >=4.6, just installing jupyterlab-chat==0.23.0, remarkably, still does not work out of the box

What does it mean? What specifically is broken? What does not work? It looks fine on https://gist.github.com/krassowski/4c254b205d78bca013efceaddfaaf015. The compatibility messages seem meaningless if everything in UI works? I am not dismissing your concern, I am trying to understand if this needs my attention to fix something in JupyterLab.

<img width="1231" height="679" alt="Image" src="https://github.com/user-attachments/assets/7cdb19bc-8c9c-48e8-a41d-01c0250cbe24" />

> However, until an official release of Jupyter Collaboration v5 is out,

Help releasing it is welcome. I spent my weekend investigating https://github.com/jupyterlab/jupyter-collaboration/issues/601 and merging other PRs. I would appreciate a look at https://github.com/jupyterlab/jupyter-collaboration/pull/611 and https://github.com/jupyterlab/jupyter-collaboration/pull/610.

**Comment by brichet** [comment]
I opened #472, locally it works with `jupyterlab<4.6` and `jupyterlab>=4.6`

**Comment by brichet** [comment]
> I suspect we can solve this using the resolutions field in package.json.

I spent some time trying this unsuccessfully. It was easier to revert the culprit PRs instead for now.

**Comment by dlqqq** [comment]
@brichet Thanks for looking into this, I'm going to test things out locally too.

I spoke with @krassowski about this at the community call - it should be OK to still use `jupyter-builder` to build the extension to support JupyterLab <4.6, otherwise there could be a bug. I'm going to see if there's a way to add automated workflows for this, may open a separate PR.

**Comment by krassowski** [comment]
Ah I see the confusion: you wrote "For users with JL >=4.6, just installing jupyterlab-chat==0.23.0, remarkably, still does not work out of the box" - this is not right; the problem is that it's the opposite: "For users with JL <4.6" it breaks. I can reproduce `[error] Error: The getter for the shared module is not a function. This may be caused by setting "shared.import: false" without the host providing the corresponding lib. #RUNTIME` from https://github.com/jupyterlab/jupyter-chat/pull/472#issuecomment-5123140912 trivially. This is an unintended breakage in `jupyter-builder` and can be fixed by moving it back to v1 of Module Federation (which is 1-line change). This will require a release of jupyter-builder and then update here. It's a pity we only noticed it now.
