### PR TITLE
Revert dependency bumps to support jupyterlab <4.6

### LINKED ISSUE #471: Support JL<4.6 in latest stable Jupyter Chat?
## Description

This PR bumped the minimum requirements of the `jupyterlab-chat` labextension to packages only available in JupyterLab v4.6+ : https://github.com/jupyterlab/jupyter-chat/pull/453

The problem is that now `jupyterlab-chat` requires `jupyter-collaboration`, but there is no stable release of that package that supports the new `jupyter_ydoc` v4 upgrade introduced in JL v4.6. This means that by default, almost all users get a broken environment when installing this:

- For users with JL <4.6 users, installing `jupyter-ai~=3.1` or `jupyterlab-chat~=0.23` results in this error when running `jupyter labextension list`:

```
$ jupyter labextension list
JupyterLab v4.5.10
/private/tmp/jai-compat/.venv/share/jupyter/labextensions
        jupyterlab-eventlistener-extension v0.4.0 enabled OK (python, jupyterlab_eventlistener)
        jupyterlab_pygments v0.3.0 enabled OK (python, jupyterlab_pygments)
        jupyterlab-notebook-awareness v0.1.0 enabled OK (python, jupyterlab_notebook_awareness)
        jupyterlab-chat-extension v0.23.0 enabled  X (python, jupyterlab_chat)
        jupyterlab-commands-toolkit v0.1.6 enabled OK (python, jupyterlab_commands_toolkit)
        @jupyter-ai/chat-commands v0.0.4 enabled OK (python, jupyter_ai_chat_commands)
        @jupyter-ai/persona-manager v0.1.2 enabled OK (python, jupyter_ai_persona_manager)
        @jupyter-ai/acp-client v0.2.1 enabled OK (python, jupyter_ai_acp_client)
        @jupyter-ai/router v0.0.5 enabled OK (python, jupyter_ai_router)
        @jupyter-ai-contrib/server-documents v0.3.1 enabled OK (python, jupyter_server_documents)
        @jupyter/collaboration-extension v4.4.1 enabled OK (python, jupyter-collaboration-ui)
        @jupyter/docprovider-extension v4.4.1 enabled OK (python, jupyter-docprovider)


"jupyterlab-chat-extension@0.23.0" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab                  Extension       Package
>=4.5.10 <4.6.0             >=4.6.0 <5.0.0  @jupyterlab/application
>=4.6.10 <4.7.0             >=4.7.0 <5.0.0  @jupyterlab/apputils
>=4.5.10 <4.6.0             >=4.6.0 <5.0.0  @jupyterlab/codemirror
>=6.5.10 <6.6.0             >=6.6.0 <7.0.0  @jupyterlab/coreutils
>=4.5.10 <4.6.0             >=4.6.0 <5.0.0  @jupyterlab/filebrowser
>=4.5.10 <4.6.0             >=4.6.0 <5.0.0  @jupyterlab/launcher
>=4.5.10 <4.6.0             >=4.6.0 <5.0.0  @jupyterlab/notebook
>=4.5.10 <4.6.0             >=4.6.0 <5.0.0  @jupyterlab/rendermime
>=7.5.10 <7.6.0             >=7.6.0 <8.0.0  @jupyterlab/services
>=4.5.10 <4.6.0             >=4.6.0 <5.0.0  @jupyterlab/settingregistry
>=4.5.10 <4.6.0             >=4.6.0 <5.0.0  @jupyterlab/translation
>=4.5.10 <4.6.0             >=4.6.0 <5.0.0  @jupyterlab/ui-components
```

- For users with JL >=4.6, just installing `jupyterlab-chat==0.23.0`, remarkably, still does not work out of the box. This is because `jupyterlab-chat` requires `jupyter-collaboration`, and there is still no official release that supports the new Jupyter YDoc v4 upgrade. So most JL >=4.6 users will get this error:

```
$ jupyter labextension list
JupyterLab v4.6.2
/private/tmp/jc-jl46/.venv/share/jupyter/labextensions
        jupyterlab_pygments v0.3.0 enabled OK (python, jupyterlab_pygments)
        jupyterlab-chat-extension v0.23.0 enabled OK (python, jupyterlab_chat)
        @jupyter/collaboration-extension v4.4.1 enabled  X (python, jupyter-collaboration-ui)
        @jupyter/docprovider-extension v4.4.1 enabled  X (python, jupyter-docprovider)


"@jupyter/collaboration-extension@4.4.1" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab    Extension         Package
>=4.0.0-b1 <5.0.0>=2.1.3 <3.0.0||>=3.0.0 <4.0.0@jupyter/ydoc



"@jupyter/docprovider-extension@4.4.1" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab    Extension         Package
>=4.0.0-b1 <5.0.0>=2.1.3 <3.0.0||>=3.0.0 <4.0.0@jupyter/ydoc
```

As far as I can tell, the only way to not get a broken environment is to run this command when installing the new Jupyter Chat release:

```
pip install 'jupyterlab-chat>=0.23.0,<0.24' 'jupyterlab>=4.6,<4.7' 'jupyter-collaboration>=5.0.0a0' --prerelease=allow
```

## Reproduce

Create `venv`s and run `jupyter labextension list` as shown above.

## Expected behavior

Jupyter Chat v0.23.0 should ideally work for JL <4.6 and JL >=4.6. However, until an official release of Jupyter Collaboration v5 is out, users will have to manually install the v5.0.0a0 pre-release as most package managers won't include pre-releases by default.

Since JL >=4.6 support won't happen without manual intervention, I recommend we at least support JL <4.6 out-of-the-box. That means loosening the ranges from https://github.com/jupyterlab/jupyter-chat/pull/453 to include JL <4.6 versions. I don't think we require any APIs exclusive to JL >=4.6 so this should be safe, we just need to investigate the issue that @brichet reported more closely. I suspect we can solve this using the `resolutions` field in `package.json`.

And on top of all of this, it would be good to add test coverage that ensures `jupyter labextension list` doesn't report any errors for JL <4.6, at least until the API truly requires JL >=4.6.

### PR DESCRIPTION
**Pull request by brichet**
This PR reverts #453 and partially #452 

- revert `@jupyterlab` dependencies to `<4.6.0` in _yarn.lock_
- revert the use of `jupyter-builder` to build the extension, as it is compatible with `jupyterlab>=4.6` only

Fixes #471

### CODE REVIEW

**Comment by dlqqq** [comment]
Still reviewing this. I've tried changing this branch to use `jupyter-builder`, but the new wheels fail on JL <4.6 for me locally. Will dig into this and also give @krassowski some info / reproducible example that may be helpful in making `jupyter-builder` builds backwards compatible with pre-4.6.

**Comment by dlqqq** [comment]
The exact browser console error I am seeing with `jupyter-builder` when testing the wheel on JupyterLab v4.5:


```
[warning] [ Federation Runtime ] Version 4.5.10 from @jupyterlab/application-top of shared singleton module @jupyterlab/application does not satisfy the requirement of undefined which needs ^4.6.1)
[warning] [ Federation Runtime ] Version 4.6.10 from @jupyterlab/application-top of shared singleton module @jupyterlab/apputils does not satisfy the requirement of undefined which needs ^4.7.1)
[warning] [ Federation Runtime ] Version 4.5.10 from @jupyterlab/application-top of shared singleton module @jupyterlab/translation does not satisfy the requirement of undefined which needs ^4.6.1)
[warning] [ Federation Runtime ] Version 4.5.10 from @jupyterlab/application-top of shared singleton module @jupyterlab/ui-components does not satisfy the requirement of undefined which needs ^4.6.1)
[warning] [ Federation Runtime ] Version 6.5.10 from @jupyterlab/application-top of shared singleton module @jupyterlab/coreutils does not satisfy the requirement of undefined which needs ^6.6.1)
[warning] [ Federation Runtime ] Version 4.5.10 from @jupyterlab/application-top of shared singleton module @jupyterlab/codemirror does not satisfy the requirement of undefined which needs ^4.6.1)
[warning] [ Federation Runtime ] Version 4.5.10 from @jupyterlab/application-top of shared singleton module @jupyterlab/filebrowser does not satisfy the requirement of undefined which needs ^4.6.1)
[warning] [ Federation Runtime ] Version 4.5.10 from @jupyterlab/application-top of shared singleton module @jupyterlab/notebook does not satisfy the requirement of undefined which needs ^4.6.1)
[warning] [ Federation Runtime ] Version 4.5.10 from @jupyterlab/application-top of shared singleton module @jupyterlab/rendermime does not satisfy the requirement of undefined which needs ^4.6.1)
[warning] [ Federation Runtime ] Version 4.5.10 from @jupyterlab/application-top of shared singleton module @jupyterlab/launcher does not satisfy the requirement of undefined which needs ^4.6.1)
[warning] [ Federation Runtime ] Version 4.5.10 from @jupyterlab/application-top of shared singleton module @jupyterlab/settingregistry does not satisfy the requirement of undefined which needs ^4.6.1)
[warning] [ Federation Runtime ] Version 4.5.10 from @jupyterlab/application-top of shared singleton module @jupyterlab/fileeditor does not satisfy the requirement of undefined which needs ^4.6.1)
[warning] [ Federation Runtime ] Version 3.1.0 from @jupyterlab/application-top of shared singleton module @jupyter/ydoc does not satisfy the requirement of undefined which needs ^4.0.0-b1)
[warning] Failed to create module: package: jupyterlab-chat-extension; module: ./extension
[error] Error: The getter for the shared module is not a function. This may be caused by setting "shared.import: false" without the host providing the corresponding lib. #RUNTIME-012
args: {"shareKey":"@jupyterlab/docregistry"}
View the docs to see how to solve: https://module-federation.io/guide/troubleshooting/runtime#runtime-012
    at http://localhost:8899/lab/extensions/jupyterlab-chat-extension/static/remoteEntry.2d3e63975f2adf22.js:5:9805
```

**Comment by dlqqq** [comment]
Have enough confidence that this works based on local testing and the E2E test runs added in #473. There are a few E2E test issues but the extension now works on JupyterLab <4.6. Proceeding to merge and cut a patch release for this.

**Comment by dlqqq** [comment]
Thank you @brichet!

**Review by dlqqq — APPROVED** [review]

**Comment by krassowski** [comment]
Counterproposal: consider https://github.com/jupyterlab/jupyter-builder/issues/154 :)

**Comment by dlqqq** [comment]
@krassowski Thanks, I just saw that! Yeah happy to cut another patch release to switch back to `jupyter-builder`, I do want to make sure this issue gets solved today before I log off tho, hope nobody minds.

**Comment by krassowski** [comment]
Sure, I was hoping I can help solve it today cleanly without going back but whatever unblocks you.

**Comment by dlqqq** [comment]
@krassowski I think it's a good idea to do them separately! It'll take time pressure off and give both of us more time to experiment and explore the right approach. It's easy to migrate back thanks to AI.

Gave it a look, thanks for putting it together so quickly.

**Review by dlqqq — APPROVED** [review]

**Comment by dlqqq** [comment]
BTW we definitely do want to migrate to `jupyter-builder` for all Jupyter AI repos. This is really cool work
